PizzaFactory/OENIK_PROG3_2020_2_YB7IQX/PizzaFactory.Web/Models/Pizza.cs
// <copyright file="Pizza.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace PizzaFactory.Web.Models
{
    using System.ComponentModel.DataAnnotations;

    /// <summary>
    /// The Pizza class holds information regarding a specific pizza.
    /// </summary>
    public class Pizza
    {
        /// <summary>
        /// Gets or sets primary key of the person class, on which the other attributes depend.
        /// </summary>
        [Display(Name = "Pizza id")]
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets name of the pizza which includes its number (not always the same as its Id field).
        /// </summary>
        [Display(Name = "Pizza name")]
        [Required]
        [StringLength(30, MinimumLength = 5)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets size of the pizza which can either be 30 or 45.
        /// </summary>
        [Display(Name = "Pizza size")]
        [Required]
        public int Size { get; set; }

        /// <summary>
        /// Gets or sets price of the pizza which is calcualted by the sum of the ingredients it contains which sum is multiplied by the FurtherExpenses field.
        /// </summary>
        [Display(Name = "Pizza price")]
        [Required]
        public int Price { get; set; }

        /// <summary>
        /// Gets or sets price multiplier, it contains the cost of a pizza box, manpower wage, oven kWh, etc.
        /// </summary>
        [Display(Name = "Pizza further expenses")]
        [Required]
        public float FurtherExpenses { get; set; }

        /// <summary>
        /// Gets or sets defines a multiplier that affects the price of the pizza, usually decreasing it since it is a sale.
        /// </summary>
        [Display(Name = "Pizza sale multiplier")]
        [Required]
        public float SaleMultiplier { get; set; }
    }
}

PizzaFactory/OENIK_PROG3_2020_2_YB7IQX/PizzaFactory.Web/Models/PizzasViewModel.cs
// <copyright file="PizzasViewModel.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace PizzaFactory.Web.Models
{
    using System.Collections.Generic;

    /// <summary>
    /// VM of the Pizza model.
    /// </summary>
    public class PizzasViewModel
    {
        /// <summary>
        /// Gets or sets the currently edited pizza.
        /// </summary>
        public Pizza EditedPizza { get; set; }

        /// <summary>
        /// Gets or sets the list of all pizzas.
        /// </summary>
        public List<Pizza> ListOfPizzas { get; set; }
    }
}

PizzaFactory/OENIK_PROG3_2020_2_YB7IQX/PizzaFactory.Web/Controllers/PizzasController.cs
// <copyright file="PizzasController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace PizzaFactory.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using AutoMapper;
    using Microsoft.AspNetCore.Mvc;
    using PizzaFactory.Logic.Interfaces;
    using PizzaFactory.Web.Models;

    /// <summary>
    /// Controller for the MVC.
    /// </summary>
    public class PizzasController : Controller
    {
        private IPizzaManagement logic;
        private IMapper mapper;
        private PizzasViewModel vm;

        /// <summary>
        /// Initializes a new instance of the <see cref="PizzasController"/> class.
        /// </summary>
        /// <param name="logic">Logic of the Pizza management.</param>
        /// <param name="mapper">Mapper that provides the conenction route service.</param>
        public PizzasController(IPizzaManagement logic, IMapper mapper)
        {
            this.logic = logic;
            this.mapper = mapper;

            this.vm = new PizzasViewModel();
            this.vm.EditedPizza = new Models.Pizza();

            var pizzas = logic.GetAllPizzas();
            this.vm.ListOfPizzas = mapper.Map<IList<Data.Models.Pizza>, List<Models.Pizza>>(pizzas);
        }

        /// <summary>
        /// Index action.
        /// </summary>
        /// <returns>IActionResult.</returns>
        public IActionResult Index()
        {
            this.ViewData["editAction"] = "AddNew";
            return this.View("PizzasIndex", this.vm);
        }

        /// <summary>
        /// Details action.
        /// </summary>
        /// <param name="id">id of the pizza.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult Details(int id)
        {
            return this.View("PizzasDetails", this.GetPizzaModel(id));
        }

        /// <summary>
        /// Delete action.
        /// </summary>
        /// <param name="id">id of the pizza.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult Remove(int id)
        {
            this.TempData["editResult"] = "Delete failed.";
            this.logic.RemovePizza(this.logic.GetOnePizza(id));
            this.TempData["editResult"] = "Delete succeeded.";
            return this.RedirectToAction(nameof(this.Index));
        }

        /// <summary>
        /// Edit action.
        /// </summary>
        /// <param name="id">id of the pizza.</param>
        /// <returns>ActionResult.</returns>
        public ActionResult Edit(int id)
        {
            this.TempData["editAction"] = "Edit";
            this.vm.EditedPizza = this.GetPizzaModel(id);
            return this.View("PizzasIndex", this.vm);
        }

        /// <summary>
        /// Edit diff.
        /// </summary>
        /// <param name="pizza">Pizza we are editing.</param>
        /// <param name="editAction">Action.</param>
        /// <returns>ActionResult.</returns>
        // POST Crud/Edit + send 1 car
        [HttpPost]
        public ActionResult Edit(Models.Pizza pizza, string editAction)

        // Because of Model Binder
        {
            if (this.ModelState.IsValid && pizza != null)
            {
                this.TempData["editResult"] = "Edit sucessful.";
                if (editAction == "AddNew")
                {
                    try
                    {
                        this.logic.AddPizza(pizza.Name, pizza.Size, pizza.Price, pizza.FurtherExpenses, pizza.SaleMultiplier);
                    }
                    catch (ArgumentException ex)
                    {
                        this.TempData["editResult"] = "Insert FAIL: " + ex.Message;
                    }
                }
                else
                {
                    this.logic.EditPizza(pizza.Id, this.mapper.Map<Models.Pizza, Data.Models.Pizza>(pizza));
                }

                return this.RedirectToAction(nameof(this.Index));
            }
            else
            {
                this.ViewData["editAction"] = "Edit";
                this.vm.EditedPizza = pizza;
                return this.View("PizzasIndex", this.vm);
            }
        }

        private Models.Pizza GetPizzaModel(int id)
        {
            Data.Models.Pizza onePizza = this.logic.GetOnePizza(id);
            return this.mapper.Map<Data.Models.Pizza, Models.Pizza>(onePizza);
        }
    }
}

PizzaFactory/OENIK_PROG3_2020_2_YB7IQX/PizzaFactory.Web/Views/Pizzas/PizzasDetails.cshtml
@model PizzaFactory.Web.Models.Pizza

@{
    ViewData["Title"] = "PizzasDetails";
}

<h2>Datasheet of one car</h2>

@Html.ActionLink("Back to the list", "Index")

<table border="1">
    <tr>
        <td>@Html.DisplayNameFor(m => m.Id)</td>
        <td>@Html.DisplayFor(m => m.Id)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Name)</td>
        <td>@Html.DisplayFor(m => m.Name)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Size)</td>
        <td>@Html.DisplayFor(m => m.Size)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.Price)</td>
        <td>@Html.DisplayFor(m => m.Price)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.FurtherExpenses)</td>
        <td>@Html.DisplayFor(m => m.FurtherExpenses)</td>
    </tr>
    <tr>
        <td>@Html.DisplayNameFor(m => m.SaleMultiplier)</td>
        <td>@Html.DisplayFor(m => m.SaleMultiplier)</td>
    </tr>
</table>

PizzaFactory/OENIK_PROG3_2020_2_YB7IQX/PizzaFactory.Web/Views/Pizzas/PizzasEdit.cshtml
@model PizzaFactory.Web.Models.Pizza

<h2>PizzasEdit</h2>

@using (Html.BeginForm("Edit", "Pizzas"))
{
    @Html.ValidationSummary()

    @Html.AntiForgeryToken()

    @Html.HiddenFor(m => m.Id)
    @Html.Hidden("editAction", ViewData["editAction"]);

    <div class="editor-label">@Html.LabelFor(m => m.Name)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Name)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Size)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Size)</div>

    <div class="editor-label">@Html.LabelFor(m => m.Price)</div>
    <div class="editor-field">@Html.EditorFor(m => m.Price)</div>

    <div class="editor-label">@Html.LabelFor(m => m.FurtherExpenses)</div>
    <div class="editor-field">@Html.EditorFor(m => m.FurtherExpenses)</div>

    <div class="editor-label">@Html.LabelFor(m => m.SaleMultiplier)</div>
    <div class="editor-field">@Html.EditorFor(m => m.SaleMultiplier)</div>

    <input type="submit" value="SEND" />
}

PizzaFactory/OENIK_PROG3_2020_2_YB7IQX/PizzaFactory.Web/Views/Pizzas/PizzasIndex.cshtml
@model PizzaFactory.Web.Models.PizzasViewModel

@{
    ViewData["Title"] = "Crud Index";
}

<h2>Pizzas Index</h2>

<p style="color:red">
    @TempData["editResult"]
</p>

@await Html.PartialAsync("PizzasEdit", Model.EditedPizza)

@await Html.PartialAsync("PizzasList", Model.ListOfPizzas)

PizzaFactory/OENIK_PROG3_2020_2_YB7IQX/PizzaFactory.Web/Views/Pizzas/PizzasList.cshtml
@model IEnumerable<PizzaFactory.Web.Models.Pizza>

<h2>PizzasList</h2>

@if (Model.Count() == 0)
{
    <p>Nothing to show here... :/</p>
}
else
{
    <table border="1">
        <tr>
            <th>@Html.DisplayNameFor(m => m.First().Name)</th>
            <th>Datasheet</th>
            <th>Delete</th>
            <th>Edit</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.Name)</td>
                <td>@Html.ActionLink("[SHOW]", "Details", new { id = item.Id })</td>
                <td>@Html.ActionLink("[DEL]", "Remove", new { id = item.Id })</td>
                <td>@Html.ActionLink("[EDIT]", "Edit", new { id = item.Id })</td>
            </tr>
        }
    </table>
}